"""Packs the web UI (web/) into the firmware.

Every file in web/ is gzip-compressed and written as a byte array to include/web_assets.h, with
its URL path, MIME type and an ETag. The firmware serves them straight from flash with
"Content-Encoding: gzip" (src/webapi.cpp), so the ESP32 never builds or decompresses HTML.

Runs automatically before every PlatformIO build (extra_scripts = pre:tools/embed_web.py) and
only rewrites the header when something in web/ changed. Can also be run by hand:
    python tools/embed_web.py
"""
import gzip
import hashlib
import os

MIME = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
    ".png": "image/png",
}


def build(root):
    src = os.path.join(root, "web")
    out = os.path.join(root, "include", "web_assets.h")
    files = []
    for base, _, names in os.walk(src):
        for n in sorted(names):
            ext = os.path.splitext(n)[1].lower()
            if ext in MIME:
                files.append(os.path.join(base, n))
    files.sort()

    blobs = []
    for f in files:
        rel = os.path.relpath(f, src).replace(os.sep, "/")
        path = "/" if rel == "index.html" else "/" + rel
        data = open(f, "rb").read()
        gz = gzip.compress(data, compresslevel=9, mtime=0)  # mtime=0: same input, same bytes
        blobs.append((path, MIME[os.path.splitext(f)[1].lower()], gz, len(data)))

    lines = [
        "// Generated by tools/embed_web.py from web/ - do not edit, edit web/ instead",
        "#pragma once",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "#include <pgmspace.h>",
        "",
        "struct WebAsset",
        "{",
        "    const char *path;",
        "    const char *mime;",
        "    const uint8_t *data; // gzip",
        "    size_t len;",
        "    const char *etag;",
        "};",
        "",
    ]
    total = 0
    for i, (path, mime, gz, raw) in enumerate(blobs):
        total += len(gz)
        lines.append("// %s: %d bytes, %d gzipped" % (path, raw, len(gz)))
        lines.append("static const uint8_t web_asset_%d[] PROGMEM = {" % i)
        for j in range(0, len(gz), 20):
            lines.append("    " + ", ".join("0x%02x" % b for b in gz[j:j + 20]) + ",")
        lines.append("};")
    lines.append("")
    lines.append("static const WebAsset WEB_ASSETS[] = {")
    for i, (path, mime, gz, raw) in enumerate(blobs):
        etag = hashlib.sha1(gz).hexdigest()[:16]
        lines.append('    {"%s", "%s", web_asset_%d, %d, "\\"%s\\""},' % (path, mime, i, len(gz), etag))
    lines.append("};")
    lines.append("static const size_t WEB_ASSETS_COUNT = %d;" % len(blobs))
    lines.append("// total gzipped: %d bytes" % total)
    text = "\n".join(lines) + "\n"

    old = open(out, encoding="utf-8").read() if os.path.exists(out) else None
    if old != text:
        open(out, "w", encoding="utf-8", newline="\n").write(text)
        print("embed_web: %d files, %d bytes gzipped -> include/web_assets.h" % (len(blobs), total))


try:
    Import("env")  # noqa: F821 - provided by PlatformIO/SCons
    build(env.subst("$PROJECT_DIR"))  # noqa: F821
except NameError:
    build(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
